// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using WebApplicationML3ML.Model;

namespace WebApplicationML3ML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\dfmera\AppData\Local\Temp\c95a938d-2953-4237-8631-3c818b32f0ab.tsv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rate with predicted Rate from sample data...\n\n");
            Console.WriteLine($"id: {sampleData.Id}");
            Console.WriteLine($"lead_time: {sampleData.Lead_time}");
            Console.WriteLine($"arrival_date_month: {sampleData.Arrival_date_month}");
            Console.WriteLine($"arrival_date_day_of_month: {sampleData.Arrival_date_day_of_month}");
            Console.WriteLine($"stays_in_weekend_nights: {sampleData.Stays_in_weekend_nights}");
            Console.WriteLine($"stays_in_week_nights: {sampleData.Stays_in_week_nights}");
            Console.WriteLine($"adults: {sampleData.Adults}");
            Console.WriteLine($"children: {sampleData.Children}");
            Console.WriteLine($"reserved_room_type: {sampleData.Reserved_room_type}");
            Console.WriteLine($"\n\nActual Rate: {sampleData.Rate} \nPredicted Rate: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: '\t',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
